[{
      "activity": "fishing",
      "distance": 10,
      "members":  10,
      "duration": 1,
    },
    {
      "activity": "jogging",
      "distance": 10,
      "members":  10,
      "duration": 3,
    },
    {
      "activity": "jogging",
      "distance": 20,
      "members":  20,
      "duration": 2,
    },
    {
      "activity": "walking",
      "distance": 20,
      "members":  20,
      "duration": 2,
    },
    {
      "activity": "walking",
      "distance": 20,
      "members":  20,
      "duration": 1,
    },
    {
      "activity": "jogging",
      "distance": 30,
      "members":  30,
      "duration": 3,
    },
    {
      "activity": "walking",
      "distance": 40,
      "members":  40,
      "duration": 50,
    },
    {
      "activity": "all",
      "distance": 40,
      "members":  10,
      "duration": 1,
    },
    {
      "activity": "all",
      "distance": 50,
      "members":  10,
      "duration": 1,
    }, 
  ]
