[{
      "name": "Fishing for beginners",
      "activity": "fishing",
      "distance": 10,
      "attendence":  10,
      "duration": 4,
    },
    {
      "name": "Jog till you can't no more!",
      "activity": "jogging",
      "distance": 10,
      "attendence":  10,
      "duration": 3,
    },
    {
      "name": "jogging near the beach",
      "activity": "jogging",
      "distance": 20,
      "attendence":  20,
      "duration": 2,
    },
    {
      "name": "Walk in The Park",
      "activity": "walking",
      "distance": 20,
      "attendence":  20,
      "duration": 2,
    },
    {
      "name": "Lets do some Walking!",
      "activity": "walking",
      "distance": 20,
      "attendence":  20,
      "duration": 1,
    },
    {
      "name": "Lets get sour",
      "activity": "jogging",
      "distance": 30,
      "attendence":  30,
      "duration": 3,
    },
    {
      "name": "Walk with us en bring your friends!",
      "activity": "Walking ",
      "distance": 40,
      "attendence":  40,
      "duration": 4,
    },
    {
      "name": "Cycling to burn Calories",
      "activity": "Cycling",
      "distance": 40,
      "attendence":  30,
      "duration": 3,
    },
    {
      "name": "Cycling around the City",
      "activity": "Cycling",
      "distance": 50,
      "attendence":  10,
      "duration": 2,
    }, 
    {
      "name": "Catching Fishsticks",
      "activity": "fishing",
      "distance": 50,
      "attendence":  10,
      "duration": 2,
    }, 
  ]
